### ISSUE TITLE
Express4 version?

### ISSUE THREAD

**Issue by kokujin** [nomiddlename/flair#1]
Is there going to be a new version soon? Thanks

**Comment by nomiddlename** [comment]
Sorry - I'm unlikely to update this, as I'm no longer working on the project which needed this module. I'm happy to accept pull requests or hand over the code to someone else to look after.

**Comment by hans-d** [comment]
I'm interested to take over

**Comment by nomiddlename** [comment]
Thanks @hans-d - I've added you as a collaborator on this repo. Your first task can be to approve your own pull request :) Do you have an npm username? If so, I can add you as an owner so you can publish updates.

**Comment by nomiddlename** [comment]
@hans-d I've also added you as a collaborator to the flair-ui project, since they are related.

**Comment by hans-d** [comment]
It's also hans-d

**Comment by hans-d** [comment]
publishing to npm will follow soon...

**Comment by nomiddlename** [comment]
@hans-d you've been added as an owner of flair-doc and flair-ui

**Comment by hans-d** [comment]
published...
